// Code generated by "stringer -type=StopReason"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Done-0]
	_ = x[Limited-1]
	_ = x[InternalError-2]
	_ = x[BreakpointReached-3]
}

const _StopReason_name = "DoneLimitedInternalErrorBreakpointReached"

var _StopReason_index = [...]uint8{0, 4, 11, 24, 41}

func (i StopReason) String() string {
	if i < 0 || i >= StopReason(len(_StopReason_index)-1) {
		return "StopReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StopReason_name[_StopReason_index[i]:_StopReason_index[i+1]]
}
